%% This file is autogenerated ...

%% This file contains virtual vehicle configuration information.

%% This file is saved at time 09-Feb-2023 16:54:10
                     ConfigInfos.version = '9.14.0.2166087 (R2023a) Prerelease Update 2';
                   ConfigInfos.SessionID = 'ConfiguredVirtualVehicle.m';
                   ConfigInfos.licStatus = 6;
                 ConfigInfos.ssc_license = 1;
                ConfigInfos.ProjPathText = 'C:\Users\koshiro\MATLAB\Projects\examples';
                    ConfigInfos.ProjPath = 'C:\Users\koshiro\MATLAB\Projects\examples\VirtualVehicle45\VirtualVehicle';
                 ConfigInfos.SessionName = 'ConfiguredVirtualVehicle';
               ConfigInfos.TemplateModel = 'VirtualVehicleTemplate';
                 ConfigInfos.ConfigModel = 'ConfiguredVirtualVehicleModel';
                    ConfigInfos.VehClass = 'PassengerCar';
                     ConfigInfos.VehArct = 'Electric Vehicle 2EM';
                      ConfigInfos.VehDyn = 0;
              ConfigInfos.PlantModelType = 'Simulink';
%% Vehicle Configuration
ConfigInfos.FeatureVariantSelectedMap=containers.Map;
ConfigInfos.FeatureVariantSelectedMap('Vehicle Architecture') = 'Electric Vehicle 2EM';
ConfigInfos.FeatureVariantSelectedMap('Chassis') = 'Vehicle Body 3DOF Longitudinal';
ConfigInfos.FeatureVariantSelectedMap('Tire') = 'MF Tires Longitudinal';
ConfigInfos.FeatureVariantSelectedMap('Tire Data') = 'MF Tires Longitudinal';
ConfigInfos.FeatureVariantSelectedMap('Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Brake Control Unit') = 'Open Loop';
ConfigInfos.FeatureVariantSelectedMap('Powertrain') = 'Electric Vehicle 2EM';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Control Unit') = 'EV 2EM';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain') = 'All Wheel Driven by 2EM';
ConfigInfos.FeatureVariantSelectedMap('Drive Shaft Torque Routing') = 'Two Actuator AWD';
ConfigInfos.FeatureVariantSelectedMap('Variant Source') = 'Multi Actuator AWD';
ConfigInfos.FeatureVariantSelectedMap('Front Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Rear Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Front Differential System') = 'Open Differential';
ConfigInfos.FeatureVariantSelectedMap('Rear Differential System') = 'Open Differential';
ConfigInfos.FeatureVariantSelectedMap('Active Differential Control') = 'No Control';
ConfigInfos.FeatureVariantSelectedMap('Electrical System') = 'Electrical System';
ConfigInfos.FeatureVariantSelectedMap('DC-DC Converter') = 'DC-DC Converter';
ConfigInfos.FeatureVariantSelectedMap('Energy Storage') = 'Mapped Battery (Electric Vehicle 2EM)';
ConfigInfos.FeatureVariantSelectedMap('Battery Management System') = 'Battery Management System';
ConfigInfos.FeatureVariantSelectedMap('Solver Configuration') = 'Solver Configuration';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 1') = 'Electric Vehicle 2EM';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 2') = 'Electric Vehicle 2EM';
ConfigInfos.FeatureVariantSelectedMap('Electric Motor') = '2EM';
ConfigInfos.FeatureVariantSelectedMap('Driver') = 'Longitudinal Driver';
ConfigInfos.FeatureVariantSelectedMap('Sensor') = 'No IMU Sensor';
ConfigInfos.FeatureVariantSelectedMap('Environment') = 'Standard Ambient';

%% Modified Component Parameters

            ConfigInfos.FeatureData{1,1} = 'PlntBattTimeCnst';
            ConfigInfos.FeatureData{1,2} = '0.001';
            ConfigInfos.FeatureData{1,3} = 'BatteryDCDC.sldd';
            ConfigInfos.FeatureData{1,4} = 'PlntBattTimeCnst';
            ConfigInfos.FeatureData{1,5} = 'Mapped Battery (Electric Vehicle 2EM)';
            ConfigInfos.FeatureData{1,6} = 'Energy Storage';

            ConfigInfos.FeatureData{2,1} = 'PlntBattChrgMax';
            ConfigInfos.FeatureData{2,2} = '4.8';
            ConfigInfos.FeatureData{2,3} = 'BatteryDCDC.sldd';
            ConfigInfos.FeatureData{2,4} = 'PlntBattChrgMax';
            ConfigInfos.FeatureData{2,5} = 'Mapped Battery (Electric Vehicle 2EM)';
            ConfigInfos.FeatureData{2,6} = 'Energy Storage';

            ConfigInfos.FeatureData{3,1} = 'PlntBattCapInit';
            ConfigInfos.FeatureData{3,2} = '2.88';
            ConfigInfos.FeatureData{3,3} = 'BatteryDCDC.sldd';
            ConfigInfos.FeatureData{3,4} = 'PlntBattCapInit';
            ConfigInfos.FeatureData{3,5} = 'Mapped Battery (Electric Vehicle 2EM)';
            ConfigInfos.FeatureData{3,6} = 'Energy Storage';

            ConfigInfos.FeatureData{4,1} = 'PlntBattNumCellSer';
            ConfigInfos.FeatureData{4,2} = '96';
            ConfigInfos.FeatureData{4,3} = 'BatteryDCDC.sldd';
            ConfigInfos.FeatureData{4,4} = 'PlntBattNumCellSer';
            ConfigInfos.FeatureData{4,5} = 'Mapped Battery (Electric Vehicle 2EM)';
            ConfigInfos.FeatureData{4,6} = 'Energy Storage';

            ConfigInfos.FeatureData{5,1} = 'PlntBattNumCellPar';
            ConfigInfos.FeatureData{5,2} = '31';
            ConfigInfos.FeatureData{5,3} = 'BatteryDCDC.sldd';
            ConfigInfos.FeatureData{5,4} = 'PlntBattNumCellPar';
            ConfigInfos.FeatureData{5,5} = 'Mapped Battery (Electric Vehicle 2EM)';
            ConfigInfos.FeatureData{5,6} = 'Energy Storage';

            ConfigInfos.FeatureData{6,1} = 'PlntBattOpenCirctVolt';
            ConfigInfos.FeatureData{6,2} = '[2.8 3.228 3.284 3.361 3.408 3.427 3.472 3.477 3.493 3.504 3.516 3.528 3.537 3.545 3.555 3.561 3.566 3.576 3.587 3.589 3.594 3.6 3.608 3.61 3.616 3.619 3.626 3.632 3.637 3.64 3.645 3.646 3.652 3.655 3.658 3.661 3.664 3.668 3.673 3.678 3.68 3.681 3.686 3.692 3.699 3.702 3.705 3.71 3.717 3.723 3.728 3.733 3.735 3.742 3.749 3.755 3.761 3.768 3.773 3.78 3.791 3.798 3.798 3.814 3.818 3.825 3.841 3.846 3.855 3.863 3.877 3.885 3.894 3.907 3.919 3.926 3.935 3.944 3.954 3.964 3.974 3.988 3.998 4.014 4.029 4.034 4.047 4.065 4.074 4.086 4.097 4.131 4.126 4.138 4.15 4.18 4.174 4.187 4.207 4.231 4.221]';
            ConfigInfos.FeatureData{6,3} = 'BatteryDCDC.sldd';
            ConfigInfos.FeatureData{6,4} = 'PlntBattOpenCirctVolt';
            ConfigInfos.FeatureData{6,5} = 'Mapped Battery (Electric Vehicle 2EM)';
            ConfigInfos.FeatureData{6,6} = 'Energy Storage';

            ConfigInfos.FeatureData{7,1} = 'PlntBattVoltSocBpt';
            ConfigInfos.FeatureData{7,2} = '[0 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1]';
            ConfigInfos.FeatureData{7,3} = 'BatteryDCDC.sldd';
            ConfigInfos.FeatureData{7,4} = 'PlntBattVoltSocBpt';
            ConfigInfos.FeatureData{7,5} = 'Mapped Battery (Electric Vehicle 2EM)';
            ConfigInfos.FeatureData{7,6} = 'Energy Storage';

            ConfigInfos.FeatureData{8,1} = 'PlntBattIntrnRes';
            ConfigInfos.FeatureData{8,2} = '[0.008846 0.009319 0.009027 0.00847 0.01032 0.01314;0.006389 0.006554 0.005553 0.005525 0.006043 0.007805;0.004364 0.004101 0.00406 0.003452 0.003846 0.004517;0.002031 0.002563 0.002532 0.00246 0.002716 0.003047;0.001443 0.001825 0.001795 0.001778 0.001924 0.002234;0.0005603 0.0007192 0.0006887 0.0007557 0.0007355 0.001014;0.001028 0.001338 0.001 0.001536 0.001546 0.002789]';
            ConfigInfos.FeatureData{8,3} = 'BatteryDCDC.sldd';
            ConfigInfos.FeatureData{8,4} = 'PlntBattIntrnRes';
            ConfigInfos.FeatureData{8,5} = 'Mapped Battery (Electric Vehicle 2EM)';
            ConfigInfos.FeatureData{8,6} = 'Energy Storage';

            ConfigInfos.FeatureData{9,1} = 'PlntBattTempBpt';
            ConfigInfos.FeatureData{9,2} = '[243.1 253.1 263.1 273.1 283.1 298.1 313.1]';
            ConfigInfos.FeatureData{9,3} = 'BatteryDCDC.sldd';
            ConfigInfos.FeatureData{9,4} = 'PlntBattTempBpt';
            ConfigInfos.FeatureData{9,5} = 'Mapped Battery (Electric Vehicle 2EM)';
            ConfigInfos.FeatureData{9,6} = 'Energy Storage';

           ConfigInfos.FeatureData{10,1} = 'PlntBattSocBpt';
           ConfigInfos.FeatureData{10,2} = '[0 0.2 0.4 0.6 0.8 1]';
           ConfigInfos.FeatureData{10,3} = 'BatteryDCDC.sldd';
           ConfigInfos.FeatureData{10,4} = 'PlntBattSocBpt';
           ConfigInfos.FeatureData{10,5} = 'Mapped Battery (Electric Vehicle 2EM)';
           ConfigInfos.FeatureData{10,6} = 'Energy Storage';

           ConfigInfos.FeatureData{11,1} = 'PlntEM1Spd';
           ConfigInfos.FeatureData{11,2} = '[0 139.62634015954637 279.25268031909275 418.87902047863906 468.88888888888891 558.50536063818549 698.13170079773181 837.75804095727813 977.38438111682456 1117.010721276371 1256.6370614359173 1396.2634015954636 1535.88974175501 1675.5160819145563]';
           ConfigInfos.FeatureData{11,3} = 'ElectricMachine1.sldd';
           ConfigInfos.FeatureData{11,4} = 'PlntEM1Spd';
           ConfigInfos.FeatureData{11,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{11,6} = 'Electric Machine 1';

           ConfigInfos.FeatureData{12,1} = 'PlntEM1Trq';
           ConfigInfos.FeatureData{12,2} = '[450 450 450 450 450 377.79404616438654 302.23523693150923 251.8626974429244 215.88231209393518 188.89702308219327 167.90846496194959 151.11761846575462 137.37965315068604 125.9313487214622]';
           ConfigInfos.FeatureData{12,3} = 'ElectricMachine1.sldd';
           ConfigInfos.FeatureData{12,4} = 'PlntEM1Trq';
           ConfigInfos.FeatureData{12,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{12,6} = 'Electric Machine 1';

           ConfigInfos.FeatureData{13,1} = 'PlntEM1SpdEff';
           ConfigInfos.FeatureData{13,2} = '[0 139.62634015954637 279.25268031909275 418.87902047863906 468.88888888888891 558.50536063818549 698.13170079773181 837.75804095727813 977.38438111682456 1117.010721276371 1256.6370614359173 1396.2634015954636 1535.88974175501 1675.5160819145563]';
           ConfigInfos.FeatureData{13,3} = 'ElectricMachine1.sldd';
           ConfigInfos.FeatureData{13,4} = 'PlntEM1SpdEff';
           ConfigInfos.FeatureData{13,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{13,6} = 'Electric Machine 1';

           ConfigInfos.FeatureData{14,1} = 'PlntEM1TrqEff';
           ConfigInfos.FeatureData{14,2} = '[0 45 90 135 180 225 270 315 360 405 450]';
           ConfigInfos.FeatureData{14,3} = 'ElectricMachine1.sldd';
           ConfigInfos.FeatureData{14,4} = 'PlntEM1TrqEff';
           ConfigInfos.FeatureData{14,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{14,6} = 'Electric Machine 1';

           ConfigInfos.FeatureData{15,1} = 'PlntEM1EffTbl';
           ConfigInfos.FeatureData{15,2} = '[52 78 80 82 82 80 78 78 76 74 70;52 78 80 82 82 80 78 78 76 74 70;52 78 84 86 86 86 86 84 84 82 82;52 80 86 86 88 88 88 86 86 84 84;52 80 86 88 88 88 88 88 86 86 86;52 80 86 88 90 90 90 90 88 88 88;52 82 88 90 91 91 92 92 92 91 91;52 82 88 91 91 92 93 93 93 93 93;52 84 90 92 92 93 93 93 93 93 93;62 86 91 93 93 93 93 93 93 93 93;66 86 91 93 93 93 93 93 93 93 93;70 86 92 93 93 93 93 93 93 93 93;70 86 92 93 93 93 93 93 93 93 93;72 86 91 93 93 93 93 93 93 93 93]';
           ConfigInfos.FeatureData{15,3} = 'ElectricMachine1.sldd';
           ConfigInfos.FeatureData{15,4} = 'PlntEM1EffTbl';
           ConfigInfos.FeatureData{15,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{15,6} = 'Electric Machine 1';

           ConfigInfos.FeatureData{16,1} = 'PlntEM1TrqLossTbl';
           ConfigInfos.FeatureData{16,2} = '[0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0]';
           ConfigInfos.FeatureData{16,3} = 'ElectricMachine1.sldd';
           ConfigInfos.FeatureData{16,4} = 'PlntEM1TrqLossTbl';
           ConfigInfos.FeatureData{16,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{16,6} = 'Electric Machine 1';

           ConfigInfos.FeatureData{17,1} = 'PlntEM2Spd';
           ConfigInfos.FeatureData{17,2} = '[0 139.62634015954637 279.25268031909275 418.87902047863906 468.88888888888891 558.50536063818549 698.13170079773181 837.75804095727813 977.38438111682456 1117.010721276371 1256.6370614359173 1396.2634015954636 1535.88974175501 1675.5160819145563]';
           ConfigInfos.FeatureData{17,3} = 'ElectricMachine2.sldd';
           ConfigInfos.FeatureData{17,4} = 'PlntEM2Spd';
           ConfigInfos.FeatureData{17,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{17,6} = 'Electric Machine 2';

           ConfigInfos.FeatureData{18,1} = 'PlntEM2Trq';
           ConfigInfos.FeatureData{18,2} = '[450 450 450 450 450 377.79404616438654 302.23523693150923 251.8626974429244 215.88231209393518 188.89702308219327 167.90846496194959 151.11761846575462 137.37965315068604 125.9313487214622]';
           ConfigInfos.FeatureData{18,3} = 'ElectricMachine2.sldd';
           ConfigInfos.FeatureData{18,4} = 'PlntEM2Trq';
           ConfigInfos.FeatureData{18,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{18,6} = 'Electric Machine 2';

           ConfigInfos.FeatureData{19,1} = 'PlntEM2SpdEff';
           ConfigInfos.FeatureData{19,2} = '[0 139.62634015954637 279.25268031909275 418.87902047863906 468.88888888888891 558.50536063818549 698.13170079773181 837.75804095727813 977.38438111682456 1117.010721276371 1256.6370614359173 1396.2634015954636 1535.88974175501 1675.5160819145563]';
           ConfigInfos.FeatureData{19,3} = 'ElectricMachine2.sldd';
           ConfigInfos.FeatureData{19,4} = 'PlntEM2SpdEff';
           ConfigInfos.FeatureData{19,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{19,6} = 'Electric Machine 2';

           ConfigInfos.FeatureData{20,1} = 'PlntEM2TrqEff';
           ConfigInfos.FeatureData{20,2} = '[0 45 90 135 180 225 270 315 360 405 450]';
           ConfigInfos.FeatureData{20,3} = 'ElectricMachine2.sldd';
           ConfigInfos.FeatureData{20,4} = 'PlntEM2TrqEff';
           ConfigInfos.FeatureData{20,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{20,6} = 'Electric Machine 2';

           ConfigInfos.FeatureData{21,1} = 'PlntEM2EffTbl';
           ConfigInfos.FeatureData{21,2} = '[52 78 80 82 82 80 78 78 76 74 70;52 78 80 82 82 80 78 78 76 74 70;52 78 84 86 86 86 86 84 84 82 82;52 80 86 86 88 88 88 86 86 84 84;52 80 86 88 88 88 88 88 86 86 86;52 80 86 88 90 90 90 90 88 88 88;52 82 88 90 91 91 92 92 92 91 91;52 82 88 91 91 92 93 93 93 93 93;52 84 90 92 92 93 93 93 93 93 93;62 86 91 93 93 93 93 93 93 93 93;66 86 91 93 93 93 93 93 93 93 93;70 86 92 93 93 93 93 93 93 93 93;70 86 92 93 93 93 93 93 93 93 93;72 86 91 93 93 93 93 93 93 93 93]';
           ConfigInfos.FeatureData{21,3} = 'ElectricMachine2.sldd';
           ConfigInfos.FeatureData{21,4} = 'PlntEM2EffTbl';
           ConfigInfos.FeatureData{21,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{21,6} = 'Electric Machine 2';

           ConfigInfos.FeatureData{22,1} = 'PlntEM2TrqLossTbl';
           ConfigInfos.FeatureData{22,2} = '[0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0]';
           ConfigInfos.FeatureData{22,3} = 'ElectricMachine2.sldd';
           ConfigInfos.FeatureData{22,4} = 'PlntEM2TrqLossTbl';
           ConfigInfos.FeatureData{22,5} = 'Electric Vehicle 2EM';
           ConfigInfos.FeatureData{22,6} = 'Electric Machine 2';

           ConfigInfos.FeatureData{23,1} = 'PlntWhlLongScaleFctr';
           ConfigInfos.FeatureData{23,2} = '0.9';
           ConfigInfos.FeatureData{23,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{23,4} = 'PlntWhlLongScaleFctr';
           ConfigInfos.FeatureData{23,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{23,6} = 'Tire Data';

           ConfigInfos.FeatureData{24,1} = 'PlntWhlDampCoeffFrnt';
           ConfigInfos.FeatureData{24,2} = '0.001';
           ConfigInfos.FeatureData{24,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{24,4} = 'PlntWhlDampCoeffFrnt';
           ConfigInfos.FeatureData{24,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{24,6} = 'Tire Data';

           ConfigInfos.FeatureData{25,1} = 'PlntWhlDampCoeffRear';
           ConfigInfos.FeatureData{25,2} = '0.001';
           ConfigInfos.FeatureData{25,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{25,4} = 'PlntWhlDampCoeffRear';
           ConfigInfos.FeatureData{25,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{25,6} = 'Tire Data';

           ConfigInfos.FeatureData{26,1} = 'PlntWhlInertiaFrnt';
           ConfigInfos.FeatureData{26,2} = '0.8';
           ConfigInfos.FeatureData{26,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{26,4} = 'PlntWhlInertiaFrnt';
           ConfigInfos.FeatureData{26,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{26,6} = 'Tire Data';

           ConfigInfos.FeatureData{27,1} = 'PlntWhlInertiaRear';
           ConfigInfos.FeatureData{27,2} = '0.8';
           ConfigInfos.FeatureData{27,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{27,4} = 'PlntWhlInertiaRear';
           ConfigInfos.FeatureData{27,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{27,6} = 'Tire Data';

           ConfigInfos.FeatureData{28,1} = 'PlntWhlInitAngVel';
           ConfigInfos.FeatureData{28,2} = '0';
           ConfigInfos.FeatureData{28,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{28,4} = 'PlntWhlInitAngVel';
           ConfigInfos.FeatureData{28,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{28,6} = 'Tire Data';

           ConfigInfos.FeatureData{29,1} = 'PlntWhlRlxLngth';
           ConfigInfos.FeatureData{29,2} = '0.15';
           ConfigInfos.FeatureData{29,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{29,4} = 'PlntWhlRlxLngth';
           ConfigInfos.FeatureData{29,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{29,6} = 'Tire Data';

           ConfigInfos.FeatureData{30,1} = 'PlntWhlLdRadius';
           ConfigInfos.FeatureData{30,2} = '0.327';
           ConfigInfos.FeatureData{30,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{30,4} = 'PlntWhlLdRadius';
           ConfigInfos.FeatureData{30,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{30,6} = 'Tire Data';

           ConfigInfos.FeatureData{31,1} = 'PlntWhlUnldRadius';
           ConfigInfos.FeatureData{31,2} = '0.336';
           ConfigInfos.FeatureData{31,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{31,4} = 'PlntWhlUnldRadius';
           ConfigInfos.FeatureData{31,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{31,6} = 'Tire Data';

           ConfigInfos.FeatureData{32,1} = 'PlntWhlPrsFrnt';
           ConfigInfos.FeatureData{32,2} = '220000';
           ConfigInfos.FeatureData{32,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{32,4} = 'PlntWhlPrsFrnt';
           ConfigInfos.FeatureData{32,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{32,6} = 'Tire Data';

           ConfigInfos.FeatureData{33,1} = 'PlntWhlPrsRear';
           ConfigInfos.FeatureData{33,2} = '220000';
           ConfigInfos.FeatureData{33,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{33,4} = 'PlntWhlPrsRear';
           ConfigInfos.FeatureData{33,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{33,6} = 'Tire Data';

           ConfigInfos.FeatureData{34,1} = 'PlntWhlLongPeakFctr';
           ConfigInfos.FeatureData{34,2} = '1';
           ConfigInfos.FeatureData{34,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{34,4} = 'PlntWhlLongPeakFctr';
           ConfigInfos.FeatureData{34,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{34,6} = 'Tire Data';

           ConfigInfos.FeatureData{35,1} = 'PlntWhlLongShapeFctr';
           ConfigInfos.FeatureData{35,2} = '1.9';
           ConfigInfos.FeatureData{35,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{35,4} = 'PlntWhlLongShapeFctr';
           ConfigInfos.FeatureData{35,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{35,6} = 'Tire Data';

           ConfigInfos.FeatureData{36,1} = 'PlntWhlLongStfFctr';
           ConfigInfos.FeatureData{36,2} = '10';
           ConfigInfos.FeatureData{36,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{36,4} = 'PlntWhlLongStfFctr';
           ConfigInfos.FeatureData{36,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{36,6} = 'Tire Data';

           ConfigInfos.FeatureData{37,1} = 'PlntWhlLongCuvFctr';
           ConfigInfos.FeatureData{37,2} = '0.97';
           ConfigInfos.FeatureData{37,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{37,4} = 'PlntWhlLongCuvFctr';
           ConfigInfos.FeatureData{37,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{37,6} = 'Tire Data';

           ConfigInfos.FeatureData{38,1} = 'PlntWhlVelIndpntForceCff';
           ConfigInfos.FeatureData{38,2} = '0.01';
           ConfigInfos.FeatureData{38,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{38,4} = 'PlntWhlVelIndpntForceCff';
           ConfigInfos.FeatureData{38,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{38,6} = 'Tire Data';

           ConfigInfos.FeatureData{39,1} = 'PlntWhlLnrVelForceComp';
           ConfigInfos.FeatureData{39,2} = '0';
           ConfigInfos.FeatureData{39,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{39,4} = 'PlntWhlLnrVelForceComp';
           ConfigInfos.FeatureData{39,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{39,6} = 'Tire Data';

           ConfigInfos.FeatureData{40,1} = 'PlntWhlQuadVelForceComp';
           ConfigInfos.FeatureData{40,2} = '0';
           ConfigInfos.FeatureData{40,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{40,4} = 'PlntWhlQuadVelForceComp';
           ConfigInfos.FeatureData{40,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{40,6} = 'Tire Data';

           ConfigInfos.FeatureData{41,1} = 'PlntWhlTirPrsExp';
           ConfigInfos.FeatureData{41,2} = '0';
           ConfigInfos.FeatureData{41,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{41,4} = 'PlntWhlTirPrsExp';
           ConfigInfos.FeatureData{41,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{41,6} = 'Tire Data';

           ConfigInfos.FeatureData{42,1} = 'PlntWhlNrmlForceExp';
           ConfigInfos.FeatureData{42,2} = '1';
           ConfigInfos.FeatureData{42,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{42,4} = 'PlntWhlNrmlForceExp';
           ConfigInfos.FeatureData{42,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{42,6} = 'Tire Data';

           ConfigInfos.FeatureData{43,1} = 'PlntWhlMinFz';
           ConfigInfos.FeatureData{43,2} = '100';
           ConfigInfos.FeatureData{43,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{43,4} = 'PlntWhlMinFz';
           ConfigInfos.FeatureData{43,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{43,6} = 'Tire Data';

           ConfigInfos.FeatureData{44,1} = 'PlntWhlMaxFz';
           ConfigInfos.FeatureData{44,2} = '6570';
           ConfigInfos.FeatureData{44,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{44,4} = 'PlntWhlMaxFz';
           ConfigInfos.FeatureData{44,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{44,6} = 'Tire Data';

           ConfigInfos.FeatureData{45,1} = 'PlntWhlMaxSlipRatio';
           ConfigInfos.FeatureData{45,2} = '1.5';
           ConfigInfos.FeatureData{45,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{45,4} = 'PlntWhlMaxSlipRatio';
           ConfigInfos.FeatureData{45,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{45,6} = 'Tire Data';

           ConfigInfos.FeatureData{46,1} = 'PlntWhlVelTolLowVel';
           ConfigInfos.FeatureData{46,2} = '1';
           ConfigInfos.FeatureData{46,3} = 'PassVeh.sldd';
           ConfigInfos.FeatureData{46,4} = 'PlntWhlVelTolLowVel';
           ConfigInfos.FeatureData{46,5} = 'MF Tires Longitudinal';
           ConfigInfos.FeatureData{46,6} = 'Tire Data';

%% Test Plan

             ConfigInfos.TestPlan{1}.Num = 1;
          ConfigInfos.TestPlan{1}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{1}.Name = 'Drive Cycle';
           ConfigInfos.TestPlan{1}.Cycle = 'FTP75';
      ConfigInfos.TestPlan{1}.Data{1}{1} = 'DriverPreviewDist';
      ConfigInfos.TestPlan{1}.Data{1}{2} = '4';
      ConfigInfos.TestPlan{1}.Data{2}{1} = 'DriverTimeConst';
      ConfigInfos.TestPlan{1}.Data{2}{2} = '0.3';
      ConfigInfos.TestPlan{1}.Data{3}{1} = 'DriverFrontCornerStiff';
      ConfigInfos.TestPlan{1}.Data{3}{2} = '40000';
      ConfigInfos.TestPlan{1}.Data{4}{1} = 'DriverRearCornerStiff';
      ConfigInfos.TestPlan{1}.Data{4}{2} = '40000';
      ConfigInfos.TestPlan{1}.Data{5}{1} = 'PlntVehInitLatPos';
      ConfigInfos.TestPlan{1}.Data{5}{2} = '0';

%% Selected Logging Signals
ConfigInfos.SelectedSignals = {
'Battery.BattSoc',...
'Battery.BattVolt',...
'Battery.BattCurr',...
'Body.BdyFrm.Cg.Vel.xdot',...
'Body.BdyFrm.Cg.Acc.ax',...
'Body.BdyFrm.Cg.Acc.ay',...
'Body.BdyFrm.Cg.Acc.az',...
'Driver.SteerFdbk',...
'Driver.AccelFdbk',...
'Driver.DecelFdbk',...
'Driver.GearFdbk',...
'Driveline.EMSpd',...
'EM.EMTrq',...
'Engine.EngTrq',...
'Engine.EngSpdOut',...
};

%% Finish
